-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    id bigint NOT NULL,
    name text COLLATE pg_catalog."default",
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.makima
(
    product_id bigint,
    categor_id bigint,
    qty bigint
);

CREATE TABLE IF NOT EXISTS public.manufacturer
(
    id bigint NOT NULL,
    name text COLLATE pg_catalog."default",
    CONSTRAINT manufacturer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_import
(
    number_order bigint NOT NULL,
    date_order date,
    date_dilevery date,
    adress_id bigint NOT NULL,
    kod bigint,
    status_id bigint NOT NULL,
    user_id bigint,
    CONSTRAINT order_import_pkey PRIMARY KEY (number_order)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id bigint NOT NULL,
    name text COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.status
(
    id bigint NOT NULL,
    name text COLLATE pg_catalog."default",
    CONSTRAINT status_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.supplier
(
    id bigint NOT NULL,
    name text COLLATE pg_catalog."default",
    CONSTRAINT supplier_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tovar
(
    id bigint NOT NULL,
    article text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    unit text COLLATE pg_catalog."default",
    price bigint,
    supplier_id bigint,
    manufacturer_id bigint,
    category_id bigint,
    sale bigint,
    kolvo bigint,
    product_description text COLLATE pg_catalog."default",
    photo text COLLATE pg_catalog."default",
    CONSTRAINT tovar_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL,
    role_id bigint,
    fio text COLLATE pg_catalog."default",
    login text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.makima
    ADD CONSTRAINT makima_categor_id_fkey FOREIGN KEY (categor_id)
    REFERENCES public.tovar (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.makima
    ADD CONSTRAINT makima_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.order_import (number_order) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_import
    ADD CONSTRAINT order_import_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_import
    ADD CONSTRAINT order_import_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tovar
    ADD CONSTRAINT tovar_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tovar
    ADD CONSTRAINT tovar_manufacturer_id_fkey FOREIGN KEY (manufacturer_id)
    REFERENCES public.manufacturer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tovar
    ADD CONSTRAINT tovar_supplier_id_fkey FOREIGN KEY (supplier_id)
    REFERENCES public.supplier (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT roles_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;